# Tool API Contracts

## Configuration Tools

### ConfigQueryTool Contract

```yaml
openapi: 3.0.0
info:
  title: Config Query Tool
  version: 1.0.0
  description: Tool for querying configuration values
paths: {}
components:
  schemas:
    ConfigQueryInput:
      type: object
      properties:
        key:
          type: string
          description: Optional specific configuration key to query
          nullable: true
      additionalProperties: false
    ConfigQueryOutput:
      type: object
      description: Configuration values object
      additionalProperties: true
    ConfigQueryTool:
      type: object
      required:
        - name
        - description
        - schema
      properties:
        name:
          type: string
          enum: [config_query]
        description:
          type: string
          description: Queries current configuration values
        schema:
          $ref: '#/components/schemas/ConfigQueryInput'
```

### ConfigUpdateTool Contract

```yaml
openapi: 3.0.0
info:
  title: Config Update Tool
  version: 1.0.0
  description: Tool for updating configuration values
paths: {}
components:
  schemas:
    ConfigUpdateInput:
      type: object
      required:
        - updates
      properties:
        updates:
          type: object
          description: Key-value pairs of configuration updates
          additionalProperties: true
      additionalProperties: false
    ConfigUpdateOutput:
      type: boolean
      description: Indicates whether the update was successful
    ConfigUpdateTool:
      type: object
      required:
        - name
        - description
        - schema
      properties:
        name:
          type: string
          enum: [config_update]
        description:
          type: string
          description: Updates configuration values with validation
        schema:
          $ref: '#/components/schemas/ConfigUpdateInput'
```

## Diagnostic Tools

### DiagnosticTool Contract

```yaml
openapi: 3.0.0
info:
  title: Diagnostic Tool
  version: 1.0.0
  description: Tool for performing system diagnostics
paths: {}
components:
  schemas:
    DiagnosticInput:
      type: object
      description: No input parameters required
      additionalProperties: false
    DiagnosticOutput:
      type: object
      description: Diagnostic results with status for each component
      properties:
        timestamp:
          type: string
          format: date-time
        components:
          type: object
          additionalProperties:
            type: object
            properties:
              status:
                type: string
                enum: [healthy, warning, error]
              message:
                type: string
              details:
                type: object
                additionalProperties: true
      required:
        - timestamp
        - components
    DiagnosticTool:
      type: object
      required:
        - name
        - description
        - schema
      properties:
        name:
          type: string
          enum: [diagnostic_check]
        description:
          type: string
          description: Performs system health diagnostics
        schema:
          $ref: '#/components/schemas/DiagnosticInput'
```

## Analytics Tools

### MessageCountTool Contract

```yaml
openapi: 3.0.0
info:
  title: Message Count Tool
  version: 1.0.0
  description: Tool for querying message counts from database
paths: {}
components:
  schemas:
    TimeRange:
      type: object
      properties:
        start:
          type: string
          format: date-time
        end:
          type: string
          format: date-time
      required:
        - start
        - end
    MessageCountInput:
      type: object
      properties:
        timeRange:
          $ref: '#/components/schemas/TimeRange'
      additionalProperties: false
    MessageCountOutput:
      type: integer
      description: Number of messages in the specified time range
    MessageCountTool:
      type: object
      required:
        - name
        - description
        - schema
      properties:
        name:
          type: string
          enum: [message_count]
        description:
          type: string
          description: Returns count of stored messages
        schema:
          $ref: '#/components/schemas/MessageCountInput'
```

### TokenUsageTool Contract

```yaml
openapi: 3.0.0
info:
  title: Token Usage Tool
  version: 1.0.0
  description: Tool for querying token usage statistics
paths: {}
components:
  schemas:
    TokenUsageInput:
      type: object
      properties:
        timeRange:
          $ref: '#/components/schemas/TimeRange'
      additionalProperties: false
    TokenUsageOutput:
      type: object
      properties:
        totalTokens:
          type: integer
          description: Total number of tokens used
        inputTokens:
          type: integer
          description: Number of input tokens used
        outputTokens:
          type: integer
          description: Number of output tokens used
        timestamp:
          type: string
          format: date-time
      required:
        - totalTokens
        - inputTokens
        - outputTokens
        - timestamp
    TokenUsageTool:
      type: object
      required:
        - name
        - description
        - schema
      properties:
        name:
          type: string
          enum: [token_usage]
        description:
          type: string
          description: Returns token usage statistics
        schema:
          $ref: '#/components/schemas/TokenUsageInput'
```